###

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/lahlou4chaimaa/lahlou4chaimaa/output/pacman-contribution-graph-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/lahlou4chaimaa/lahlou4chaimaa/output/pacman-contribution-graph.svg">
  <img alt="pacman contribution graph" src="https://raw.githubusercontent.com/lahlou4chaimaa/lahlou4chaimaa/output/pacman-contribution-graph.svg">
</picture>

###

<br clear="both">

<img src="https://raw.githubusercontent.com/lahlou4chaimaa/lahlou4chaimaa/output/snake.svg" alt="Snake animation" />

###
